services:
  localstack:
    image: localstack/localstack
    container_name: localstack
    hostname: localstack
    environment:
      - SERVICES=sqs
      - HOSTNAME_EXTERNAL=localstack
    env_file:
      - .env
    ports:
      - "127.0.0.1:4566:4566"
      - "127.0.0.1:4510-4559:4510-4559"
    volumes:
      - "./localstack-setup.sh:/etc/localstack/init/ready.d/init-aws.sh"
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4566/_localstack/health"]
      interval: 2s
      timeout: 3s
      retries: 3
    networks:
      video-compactor-network:
        aliases:
        - localstack

  mongo_database:
    image: mongo:latest
    container_name: mongo_database
    ports:
      - "27017:27017"
    volumes:
      - ./video-compactor/init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh
      - ./video-compactor/init.js:/docker-entrypoint-initdb.d/init.js
    environment:
        - MONGO_INITDB_DATABASE=video_compactor
    command: mongod --bind_ip_all
    healthcheck:
      test: ["CMD-SHELL", "mongosh --eval 'db.adminCommand(\"ping\")' --quiet"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
    networks:
      - video-compactor-network

  video_compactor:
    container_name: video_compactor
    env_file:
      - .env
    environment:
      - video_compactor_HOSTNAME=video_compactor_database
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "4000:4000"
    command: sh -c "mix ecto.create && mix ecto.migrate && mix run --no-halt"
    depends_on:
      localstack:
        condition: service_healthy
      mongo_database:
        condition: service_started
    volumes:
      - ./tmp:/tmp
    networks:
      video-compactor-network:
        aliases:
          - video_compactor
    dns_search: .

networks:
  video-compactor-network:
    name: video-compactor-network
    driver: bridge
