services:
  localstack:
    image: localstack/localstack
    container_name: localstack
    hostname: localstack
    environment:
      - SERVICES=sqs
      - HOSTNAME_EXTERNAL=localstack
    env_file:
      - .env
    ports:
      - "127.0.0.1:4566:4566"
      - "127.0.0.1:4510-4559:4510-4559"
    volumes:
      - "./localstack-setup.sh:/etc/localstack/init/ready.d/init-aws.sh"
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4566/_localstack/health"]
      interval: 2s
      timeout: 3s
      retries: 3
    networks:
      video-compactor-network:
        aliases:
        - localstack

  database:
    image: postgres:15
    container_name: video_compactor_database
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    networks:
      - video-compactor-network

  video_compactor:
    container_name: video_compactor
    env_file:
      - .env
    environment:
      - video_compactor_HOSTNAME=video_compactor_database
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "4000:4000"
    command: sh -c "mix ecto.create && mix ecto.migrate && mix run --no-halt"
    depends_on:
      localstack:
        condition: service_healthy
      database:
        condition: service_started
    networks:
      video-compactor-network:
        aliases:
          - video_compactor
    dns_search: .

networks:
  video-compactor-network:
    name: video-compactor-network
    driver: bridge
