name: CI - Build e Testes

on:
  push:
    branches: 
      - main
      - cicd_fase_5
  pull_request:
    branches:
      - main
      - cicd_fase_5

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:6
        ports: ['27017:27017']
        options: >-
          --health-cmd "mongosh --eval 'db.runCommand({ ping: 1 })'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    env:
      MIX_ENV: test
      MONGO_URL: mongodb://localhost:27017/my_app_test

    steps:
      - uses: actions/checkout@v4

      - name: Setup Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: '1.18'
          otp-version: '27.0'

      - name: Install dependencies
        run: mix deps.get

      - name: Compile
        run: mix compile --warnings-as-errors

      - name: Check formatting
        run: mix format --check-formatted

      - name: Run tests
        run: mix test