name: Continuous Delivery

on:
  workflow_run:
    workflows: ["Continuous Integration - Build and Tests"]
    types:
      - completed

jobs:
  deploy:
    name: Docker Hub Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t diegogl12/video-compactor:latest .

      - name: Push Docker image
        run: |
          docker push diegogl12/video-compactor:latest

